# Generated by Django 3.2 on 2022-06-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtask',
            field=models.ManyToManyField(related_name='_tasks_task_subtask_+', to='tasks.Task'),
        ),
    ]
